SELECT      
        COUNT(EVALUADOR.IDUSER) CANTEVALPORDECL
    FROM
        WFPROCESS WFP           
    JOIN
        GNASSOCFORMREG REG                           
            ON WFP.CDASSOCREG = REG.CDASSOC           
    LEFT JOIN
        DYNGRIDPROYECTO PROYECTO                           
            ON REG.OIDENTITYREG=PROYECTO.OID      
	LEFT JOIN
		DYNFORMUSRGRIDEVAL EVALUADOR 
			ON EVALUADOR.OIDABCU2DY16NPX3MS = PROYECTO.OID
    WHERE
        WFP.CDPROCESSMODEL = 198
        AND WFP.IDPROCESS = :paramIdWorkflow
		AND EVALUADOR.CONFINTE = 'por declarar'

