SELECT
        WFP.IDPROCESS,
		WFP.NMPROCESS,
		EVAL.IDCONCURSO,
		EVAL.NMCONCURSO,
		EVAL.TIPOCONC TIPOCONCURSO,
		EVAL.EVALUACION TIPOEVALUACION,
		GRID.IDPROYECTO,
		GRID.NMPROYECTO,
		1 AS QT
    FROM
        WFPROCESS WFP
		JOIN
        GNASSOCFORMREG REG              
            ON WFP.CDASSOCREG = REG.CDASSOC      
    JOIN
        DYNFORM EVAL              
            ON REG.OIDENTITYREG= EVAL.OID 
	JOIN DYNGRIDPROYECTO GRID
			ON GRID.OIDABCFTFUJK3702QF = EVAL.OID
    WHERE
        CDPROCESSMODEL IN (
            197
		  /**, 198, 199, 203, 205**/
        )
		
	